# destinationrule.yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-backend-rule
  namespace: staging
spec:
  host: my-backend-service # <--- VERIFY this matches the host in VirtualService
  subsets:
    - name: stable
      labels:
        app: backend 
    - name: canary
      labels:
        app: backend